CREATE TABLE RecyclableType(
	 Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	 [Type] VARCHAR(100) NOT NULL UNIQUE, 
	 Rate DECIMAL(10, 2) NOT NULL,
	 MinKg DECIMAL(10, 2) NOT NULL,
	 MaxKg DECIMAL(10, 2) NOT NULL
)

CREATE TABLE RecyclableItem(
	Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	[Weight] DECIMAL(10,2) NOT NULL,
	ComputedRate DECIMAL(10, 2) NOT NULL,
	ItemDescription VARCHAR(150),
	RecyclableTypeId INT FOREIGN KEY REFERENCES RecyclableType(Id) NOT NULL
)