//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sds_technical_exam.Models
{
    using sds_technical_exam.Models.CustomValidationAttribute;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class RecyclableType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RecyclableType()
        {
            this.RecyclableItems = new HashSet<RecyclableItem>();
        }
    
        public int Id { get; set; }

        [Required]
        [MinLength(3, ErrorMessage = "Type must be at least 3 characters.")]
        public string Type { get; set; }

        [Required]
        [PositiveNumber]
        public decimal Rate { get; set; }

        [Required]
        [PositiveNumber]
        public decimal MinKg { get; set; }

        [Required]
        [PositiveNumber]
        public decimal MaxKg { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecyclableItem> RecyclableItems { get; set; }
    }
}
